# Generated by Django 2.1.7 on 2020-04-26 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AboutUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
