# Generated by Django 2.1.7 on 2020-04-30 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 5, 16, 2, 791792, tzinfo=utc)),
        ),
    ]
